### ISSUE TITLE
Full prompt / configuration is necessary for reproducability

### ISSUE THREAD

**Issue by joshka** [RaphaelKhoury/ProgramsGeneratedByChatGPT#1]
LLMs are sensitive to initial conditions and exact instructions used (e.g. you might get a different answer to "write a program" vs "give me the code for" vs "how do I". The paper and this repo both omit the full details of the methodolgy used (This should include at minimum the exact prompt, state of the ChatGPT session, etc.)

Even with these noted, you're going expect to see randomness in the results when using ChatGPT via a browser session at chat.openai.com vs [the playground](https://platform.openai.com/playground?mode=chat&model=gpt-3.5-turbo). The paper doesn't specify how many times the code generation task was repeated. Does it control for this at all? Did you just pick the first one? Did you try it multiple times in the same session? Did you try it in the same session after creating a previous program in another language? ...

For repeatable outputs, you might consider using the playground and setting the temperature to zero (or considering testing the amount of randomness that you get when using a default / higher temperature), or even better perhaps write a Jupyter notebook that shows the exact settings, questions etc that were used for the study.

BTW, I think this sort of research is really useful to do, so please don't take the critical feedback above as discouragement of your work. I'm intending it as the opposite. Please continue. This work is important. It would not be a surprising outcome (at least to me) to show that ChatGPT can and does generate insecure code, and it's really crucial to show with precision how bad that really is, but the experimental conditions seem like they could do with some fine tuning.

**Comment by juyongjiang** [comment]
> LLMs are sensitive to initial conditions and exact instructions used (e.g. you might get a different answer to "write a program" vs "give me the code for" vs "how do I". The paper and this repo both omit the full details of the methodolgy used (This should include at minimum the exact prompt, state of the ChatGPT session, etc.)
> 
> Even with these noted, you're going expect to see randomness in the results when using ChatGPT via a browser session at chat.openai.com vs [the playground](https://platform.openai.com/playground?mode=chat&model=gpt-3.5-turbo). The paper doesn't specify how many times the code generation task was repeated. Does it control for this at all? Did you just pick the first one? Did you try it multiple times in the same session? Did you try it in the same session after creating a previous program in another language? ...
> 
> For repeatable outputs, you might consider using the playground and setting the temperature to zero (or considering testing the amount of randomness that you get when using a default / higher temperature), or even better perhaps write a Jupyter notebook that shows the exact settings, questions etc that were used for the study.
> 
> BTW, I think this sort of research is really useful to do, so please don't take the critical feedback above as discouragement of your work. I'm intending it as the opposite. Please continue. This work is important. It would not be a surprising outcome (at least to me) to show that ChatGPT can and does generate insecure code, and it's really crucial to show with precision how bad that really is, but the experimental conditions seem like they could do with some fine tuning.

I totally agree with you. If the authors can provide the pair of <prompt, code>, it will be excellent for further study.

**Comment by clodbrasilino** [comment]
> > LLMs are sensitive to initial conditions and exact instructions used (e.g. you might get a different answer to "write a program" vs "give me the code for" vs "how do I". The paper and this repo both omit the full details of the methodolgy used (This should include at minimum the exact prompt, state of the ChatGPT session, etc.)
> > Even with these noted, you're going expect to see randomness in the results when using ChatGPT via a browser session at chat.openai.com vs [the playground](https://platform.openai.com/playground?mode=chat&model=gpt-3.5-turbo). The paper doesn't specify how many times the code generation task was repeated. Does it control for this at all? Did you just pick the first one? Did you try it multiple times in the same session? Did you try it in the same session after creating a previous program in another language? ...
> > For repeatable outputs, you might consider using the playground and setting the temperature to zero (or considering testing the amount of randomness that you get when using a default / higher temperature), or even better perhaps write a Jupyter notebook that shows the exact settings, questions etc that were used for the study.
> > BTW, I think this sort of research is really useful to do, so please don't take the critical feedback above as discouragement of your work. I'm intending it as the opposite. Please continue. This work is important. It would not be a surprising outcome (at least to me) to show that ChatGPT can and does generate insecure code, and it's really crucial to show with precision how bad that really is, but the experimental conditions seem like they could do with some fine tuning.
> 
> I totally agree with you. If the authors can provide the pair of <prompt, code>, it will be excellent for further study.

I came to the repo exactly looking for the pair you just noticed to check for reproducibility, but only found the code.

Author, can you share also the prompts with us?

**Comment by RaphaelKhoury** [comment]
thanks for the feedback.
Unfortunately, I don't have the prompts I used in this experiment because I worked with several students, some of which graduated. I'm continuing this research and being very careful to keep everything.
